include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/l10n/gen/*
  errors:
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    unrelated_type_equality_checks: ignore
    avoid_print: ignore
    invalid_annotation_target: ignore
    prefer_final_fields: ignore
    unnecessary_null_comparison: ignore
    omit_local_variable_types: ignore
    avoid_catches_without_on_clauses: ignore
    leading_newlines_in_multiline_strings: ignore
    lines_longer_than_80_chars: ignore
    only_throw_errors: ignore
    inference_failure_on_function_invocation: ignore
    unused_element: ignore
    avoid_dynamic_calls: ignore
    inference_failure_on_untyped_parameter: ignore
    avoid_slow_async_io: ignore
    discarded_futures: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    prefer_const_declarations: ignore
linter:
  rules:
    public_member_api_docs: false
