targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include:
            - lib/data/models/*
            - lib/data/models/**/*
      freezed:
        generate_for:
          include:
            - lib/data/models/*
            - lib/data/models/**/*
            - lib/domain/failures/*
            - lib/domain/failures/**/*
            - lib/domain/models/*
            - lib/domain/models/**/*
            - lib/ui/features/**/view_models/*
            - lib/ui/features/**/view_models/**/*
